/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CounterInterface extends Interface {
    getFunction(nameOrSignature: "addCount" | "count" | "decreament" | "end" | "getCount" | "reset"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'addCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'count', values?: undefined): string;
encodeFunctionData(functionFragment: 'decreament', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'end', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'reset', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'addCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'count', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decreament', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'end', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reset', data: BytesLike): Result;
  }

  

  export interface Counter extends BaseContract {
    
    connect(runner?: ContractRunner | null): Counter;
    waitForDeployment(): Promise<this>;

    interface: CounterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addCount: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    count: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    decreament: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    end: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    getCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    reset: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addCount'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'count'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'decreament'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'end'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'reset'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }