/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { Counter, CounterInterface } from "../Counter.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "addCount",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "count",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "decreament",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "end",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "reset",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5061039d8061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610060575f3560e01c806306661abd1461006457806311b94fd51461008257806370cab58d1461009e578063a87d942c146100ba578063d826f88f146100d8578063efbe1c1c146100e2575b5f5ffd5b61006c610100565b60405161007991906101b7565b60405180910390f35b61009c600480360381019061009791906101fe565b610105565b005b6100b860048036038101906100b391906101fe565b61011f565b005b6100c261017d565b6040516100cf91906101b7565b60405180910390f35b6100e0610185565b005b6100ea61018d565b6040516100f79190610243565b60405180910390f35b5f5481565b805f5f8282546101159190610289565b9250508190555050565b805f541015610163576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161015a90610316565b60405180910390fd5b805f5f8282546101739190610334565b9250508190555050565b5f5f54905090565b5f5f81905550565b60015f9054906101000a900460ff1681565b5f819050919050565b6101b18161019f565b82525050565b5f6020820190506101ca5f8301846101a8565b92915050565b5f5ffd5b6101dd8161019f565b81146101e7575f5ffd5b50565b5f813590506101f8816101d4565b92915050565b5f60208284031215610213576102126101d0565b5b5f610220848285016101ea565b91505092915050565b5f8115159050919050565b61023d81610229565b82525050565b5f6020820190506102565f830184610234565b92915050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52601160045260245ffd5b5f6102938261019f565b915061029e8361019f565b92508282019050808211156102b6576102b561025c565b5b92915050565b5f82825260208201905092915050565b7f54686520636f756e7465722063616e277420756e6465722030000000000000005f82015250565b5f6103006019836102bc565b915061030b826102cc565b602082019050919050565b5f6020820190508181035f83015261032d816102f4565b9050919050565b5f61033e8261019f565b91506103498361019f565b92508282039050818111156103615761036061025c565b5b9291505056fea264697066735822122060393f3b44c6bf8377906b415b9797e4ea3b91692fdc6d50b328955608e300a964736f6c634300081c0033";

  
      type CounterConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: CounterConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Counter__factory extends ContractFactory {
    
      constructor(...args: CounterConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Counter & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Counter__factory {
      return super.connect(runner) as Counter__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): CounterInterface {
      return new Interface(_abi) as CounterInterface;
    }
    
    override attach(address: string | Addressable): Counter {
      return super.attach(address) as Counter;
    }
  static connect(address: string, runner?: ContractRunner | null): Counter {
      return new Contract(address, _abi, runner) as unknown as Counter;
    }
  }

  
  